media:
  input: public
  output: /
content:
  - name: about
    label: About page
    type: file
    path: src/pages/about.md
    fields:      
      -  name: tags
         label: Tag
         type: object
         list: true
         fields:
               - name: first_name
                 type: string
               - name: last_name
                 type: string
